apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: full-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/GitTactician/argocd-testEnv.git
    targetRevision: HEAD
    path: ./applications  # Path to where the individual apps are defined
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
