apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-app
spec:
  destination:
    name: ''
    namespace: cert-manager
    server: https://kubernetes.default.svc
  source:
    path: ./cert-manager
    repoURL: https://github.com/GitTactician/argocd-testEnv.git
    targetRevision: main
  sources: []
  project: cert-env
  syncPolicy:
    automated:
      prune: true
      selfHeal: true