apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: nginx
    server: https://kubernetes.default.svc
  source:
    path: ./nginx
    repoURL: https://github.com/GitTactician/argocd-testEnv.git
    targetRevision: HEAD
  project: cert-env
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  
  
  