apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
spec:
  destination:
    name: ''
    namespace: nginx
    server: https://kubernetes.default.svc
  source:
    path: nginx
    repoURL: https://github.com/GitTactician/argocd-testEnv.git
    targetRevision: HEAD
  sources: []
  project: cert-env
  syncPolicy:
    automated:
      prune: true
      selfHeal: true