apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-service
  namespace: kube-system
spec:
  selector:
    app: nginx-ingress
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    - protocol: TCP
      port: 443
      targetPort: 443
