apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: userapi-cert
  namespace: cert-manager
spec:
  dnsNames:
    - cluster-demo.live
  secretName: userapi-tls
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer